### PR TITLE
Png default

### PR DESCRIPTION
**Pull request by ponchorage**

### CODE REVIEW

**Comment by janiv** [comment]
Looks good. I'll tag and release

**Comment by janiv** [comment]
Or do you want to? I can add you as an npm owner so you can npm publish.

**Comment by ponchorage** [comment]
Sure, I can do it. I've never done an npm publish.

**Comment by janiv** [comment]
Send me your npm username and I'll add you as an owner.

**Comment by ponchorage** [comment]
ponchorage

**Comment by janiv** [comment]
Ah, sorry, I forgot we don't publish this. I'll add you to the other ones though so you can publish those though. I went ahead and tagged and pushed the tag up.

**Comment by ponchorage** [comment]
Should I create a release from the tag?

**Comment by janiv** [comment]
Yes, that'd be great.

**Pull request merged**
